# Generated by Django 2.2.5 on 2019-12-26 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20191226_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 28, 12, 59, 58, 706057, tzinfo=utc)),
        ),
    ]
