# Generated by Django 5.1.2 on 2024-10-16 14:03

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creating Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basket Slot',
                'verbose_name_plural': 'Basket slots',
            },
            managers=[
                ('slots', django.db.models.manager.Manager()),
            ],
        ),
    ]
