# Generated by Django 5.1.2 on 2024-10-12 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 11, 7, 16, 189430, tzinfo=datetime.timezone.utc)),
        ),
    ]
