from django.urls import path

from shop.admin_app import views as admin_app_views

app_name = 'admin_app'

urlpatterns = [
    path(
        '',
        admin_app_views.main_admin_page,
        name='index',
    ),
    path(
        'users/create/',
        admin_app_views.UserCreateView.as_view(),
        name='user_create',
    ),
    path(
        'users/read/',
        admin_app_views.UserListView.as_view(),
        name='users',
    ),
    path(
        'users/update/<int:pk>/',
        admin_app_views.UserUpdateView.as_view(),
        name='user_update',
    ),
    path(
        'users/delete/<int:pk>/',
        admin_app_views.UserDeleteView.as_view(),
        name='user_delete',
    ),
    path(
        'categories/create/',
        admin_app_views.CategoryCreateView.as_view(),
        name='category_create',
    ),
    path(
        'categories/read/',
        admin_app_views.CategoryListView.as_view(),
        name='categories',
    ),
    path(
        'categories/update/<int:pk>/',
        admin_app_views.CategoryUpdateView.as_view(),
        name='category_update',
    ),
    path(
        'categories/delete/<int:pk>/',
        admin_app_views.CategoryDeleteView.as_view(),
        name='category_delete',
    ),
    path(
        'products/create/',
        admin_app_views.ProductCreateView.as_view(),
        name='product_create',
    ),
    path(
        'products/read/',
        admin_app_views.ProductListView.as_view(),
        name='products',
    ),
    path(
        'products/read/category/<int:category_pk>/',
        admin_app_views.ProductListView.as_view(),
        name='products_by_category',
    ),
    path(
        'products/read/<int:pk>/',
        admin_app_views.ProductDetailView.as_view(),
        name='product_read',
    ),
    path(
        'products/update/<int:pk>/',
        admin_app_views.ProductUpdateView.as_view(),
        name='product_update',
    ),
    path(
        'products/delete/<int:pk>/',
        admin_app_views.ProductDeleteView.as_view(),
        name='product_delete',
    ),
]
